### ISSUE TITLE
$EDITORUI 跨域出错

### ISSUE THREAD

**Issue by kemingcao** [zhuzhichao/Ueditor#2]
Use of attributes' nodeValue attribute is deprecated. Use value instead. ueditor.all.min.js:554:0
Error: Permission denied to access property '$EDITORUI' internal.js:4:4
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.10.2.min.js:1:0
ReferenceError: $G is not defined

**Comment by zhuzhichao** [comment]
能再具体描述一下什么情况下如何出现的问题吗？是PHP封装的问题还是ueditor本身的问题。

**Comment by miaotaizi** [comment]
`请求后台配置项http错误，上传功能将不能正常使用！d @ ueditor.all.min.js:124`
最近老是会有这样的错误是怎么回事啊, 
刚安装的话没问题....

**Comment by zhuzhichao** [comment]
@miaotaizi 最近你做什么更改或者配置什么东西吗？ 如果配置正确的话，一般是没有什么问题的。

**Comment by miaotaizi** [comment]
@zhuzhichao 哇,你居然在线, 没什么问题啊, 我昨天重新安装了下可以用
但是今天有报这样的错误了 :confounded:

**Comment by zhuzhichao** [comment]
你打开 chrome 控制台，看看 network 里面请求配置文件的URL地址是否是正确的。

**Comment by miaotaizi** [comment]
@zhuzhichao 你好,控制台里面controller的请求状态为caneled ???
这是啥情况

**Comment by miaotaizi** [comment]
@zhuzhichao 好吧, 重新执行了下
`php artisan config:publish zhuzhichao/ueditor`
`php artisan asset:publish zhuzhichao/ueditor`
好像解决了

**Comment by csrutil** [comment]
大部分是配置的问题，上次出现了那个问题后，我就直接使用原生ueditor了，没有再使用composer进行导入了，但是还是要谢谢做了一个wrapper ; )

**Comment by zhuzhichao** [comment]
@kemingcao @miaotaizi 

百度的同学好像已经放弃了ueditor了，我给他们提交过PR以及issues，并且给他们写邮件，从来没有回应。看了看他们最后的提交记录，从注释上都很有喜感。看来是真的放弃了。我看了他们之前在 issues 和一些人争吵甚至互骂，感觉到国内这个开源气氛还是很差，遇到问题都是骂开发者的。。。

![qq20150508-1 2x](https://cloud.githubusercontent.com/assets/3017759/7534223/16f89588-f5ab-11e4-8ba6-e3c8b5393e5d.png)

我们的项目现在也不用ueditor了，所以这个包也没有再过多的维护，老项目上用着还算稳定，没有什么问题。

最后祝你们周末愉快！ :smile:

**Comment by miaotaizi** [comment]
噢,好的,用着也挺好,感谢你.

**Comment by csrutil** [comment]
谢谢，🙏！
